"""add api tokens

Revision ID: 630a914a1004
Revises: a3cbe1a0ce11
Create Date: 2026-06-16 10:26:16.673402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630a914a1004'
down_revision = 'a3cbe1a0ce11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ApiTokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    with op.batch_alter_table('ApiTokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ApiTokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_ApiTokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ApiTokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ApiTokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_ApiTokens_token_hash'))

    op.drop_table('ApiTokens')
    # ### end Alembic commands ###
