"""baseline schema

Revision ID: a3cbe1a0ce11
Revises: 
Create Date: 2026-06-16 09:59:36.975779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cbe1a0ce11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movements',
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('movement_name', sa.String(length=100), nullable=False),
    sa.Column('movement_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_table('MuscleGroups',
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_name', sa.String(length=100), nullable=False),
    sa.Column('muscle_group_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('muscle_group_id'),
    sa.UniqueConstraint('muscle_group_name')
    )
    op.create_table('SecurityEvents',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('SecurityEvents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SecurityEvents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_SecurityEvents_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_SecurityEvents_ip_address'), ['ip_address'], unique=False)

    op.create_table('UserGroups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('group_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('bodyweight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gym_experience', sa.String(length=50), nullable=True),
    sa.Column('workout_goal', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('session_token', sa.String(length=100), nullable=True),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_workout_reminders', sa.Boolean(), nullable=False),
    sa.Column('email_group_activity', sa.Boolean(), nullable=False),
    sa.Column('llm_requests_hour', sa.Integer(), nullable=True),
    sa.Column('llm_requests_day', sa.Integer(), nullable=True),
    sa.Column('llm_requests_reset_hour', sa.DateTime(), nullable=True),
    sa.Column('llm_requests_reset_day', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reset_token'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_table('AdminAuditLog',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('GroupInvitations',
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=False),
    sa.Column('invitee_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['UserGroups.group_id'], ),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['Users.user_id'], ),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('invitation_id')
    )
    op.create_table('GroupJoinRequests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('responded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['UserGroups.group_id'], ),
    sa.ForeignKeyConstraint(['responded_by'], ['Users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('MovementMuscleGroup',
    sa.Column('movement_muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('target_percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movement_id'], ['Movements.movement_id'], ),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['MuscleGroups.muscle_group_id'], ),
    sa.PrimaryKeyConstraint('movement_muscle_group_id')
    )
    op.create_table('UserFeedbackProfiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('weight_multiplier', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('volume_multiplier', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('pattern_type', sa.String(length=30), nullable=True),
    sa.Column('data_points', sa.Integer(), nullable=True),
    sa.Column('last_analyzed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], ['Movements.movement_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('user_id', 'movement_id', name='uq_user_movement_feedback')
    )
    op.create_table('UserGroupMembership',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['UserGroups.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_table('Workouts',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_name', sa.String(length=100), nullable=False),
    sa.Column('workout_date', sa.DateTime(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('workout_group_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_table('WorkoutComments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(trim(body)) > 0', name='ck_workout_comments_body_not_empty'),
    sa.ForeignKeyConstraint(['author_user_id'], ['Users.user_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['UserGroups.group_id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['Workouts.workout_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    with op.batch_alter_table('WorkoutComments', schema=None) as batch_op:
        batch_op.create_index('idx_workout_comments_group_workout_created', ['group_id', 'workout_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_WorkoutComments_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_WorkoutComments_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_WorkoutComments_workout_id'), ['workout_id'], unique=False)

    op.create_table('WorkoutFeedbackSummaries',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('completion_quality', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('overall_recommendation', sa.Text(), nullable=True),
    sa.Column('movement_feedback_json', sa.Text(), nullable=True),
    sa.Column('imbalance_feedback_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['Workouts.workout_id'], ),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('workout_id')
    )
    op.create_table('WorkoutMovement',
    sa.Column('workout_movement_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], ['Movements.movement_id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['Workouts.workout_id'], ),
    sa.PrimaryKeyConstraint('workout_movement_id')
    )
    op.create_table('WorkoutMuscleGroupImpact',
    sa.Column('impact_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_reps', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_sets', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['MuscleGroups.muscle_group_id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['Workouts.workout_id'], ),
    sa.PrimaryKeyConstraint('impact_id')
    )
    op.create_table('Sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('workout_movement_id', sa.Integer(), nullable=False),
    sa.Column('set_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workout_movement_id'], ['WorkoutMovement.workout_movement_id'], ),
    sa.PrimaryKeyConstraint('set_id')
    )
    op.create_table('Reps',
    sa.Column('rep_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('rep_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['Sets.set_id'], ),
    sa.PrimaryKeyConstraint('rep_id')
    )
    op.create_table('SetEntries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('entry_order', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_bodyweight', sa.Boolean(), nullable=True),
    sa.Column('planned_reps', sa.Integer(), nullable=True),
    sa.Column('planned_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['Sets.set_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('Weights',
    sa.Column('weight_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('weight_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_bodyweight', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['Sets.set_id'], ),
    sa.PrimaryKeyConstraint('weight_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Weights')
    op.drop_table('SetEntries')
    op.drop_table('Reps')
    op.drop_table('Sets')
    op.drop_table('WorkoutMuscleGroupImpact')
    op.drop_table('WorkoutMovement')
    op.drop_table('WorkoutFeedbackSummaries')
    with op.batch_alter_table('WorkoutComments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_WorkoutComments_workout_id'))
        batch_op.drop_index(batch_op.f('ix_WorkoutComments_group_id'))
        batch_op.drop_index(batch_op.f('ix_WorkoutComments_author_user_id'))
        batch_op.drop_index('idx_workout_comments_group_workout_created')

    op.drop_table('WorkoutComments')
    op.drop_table('Workouts')
    op.drop_table('UserGroupMembership')
    op.drop_table('UserFeedbackProfiles')
    op.drop_table('MovementMuscleGroup')
    op.drop_table('GroupJoinRequests')
    op.drop_table('GroupInvitations')
    op.drop_table('AdminAuditLog')
    op.drop_table('Users')
    op.drop_table('UserGroups')
    with op.batch_alter_table('SecurityEvents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SecurityEvents_ip_address'))
        batch_op.drop_index(batch_op.f('ix_SecurityEvents_email'))
        batch_op.drop_index(batch_op.f('ix_SecurityEvents_created_at'))

    op.drop_table('SecurityEvents')
    op.drop_table('MuscleGroups')
    op.drop_table('Movements')
    # ### end Alembic commands ###
